openapi: 3.1.0
info:
  title: bijux-vex execution API
  version: v1
paths:
  /capabilities:
    get:
      summary: Capabilities
      operationId: capabilities_capabilities_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendCapabilitiesReport'
  /create:
    post:
      summary: Create
      operationId: create_create_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Create Create Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ingest:
    post:
      summary: Ingest
      operationId: ingest_ingest_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Ingest Ingest Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /artifact:
    post:
      summary: Artifact
      operationId: artifact_artifact_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionArtifactRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Artifact Artifact Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /execute:
    post:
      summary: Execute
      operationId: execute_execute_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionRequestPayload'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Execute Execute Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /explain:
    post:
      summary: Explain
      operationId: explain_explain_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExplainRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Explain Explain Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /replay:
    post:
      summary: Replay
      operationId: replay_replay_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionRequestPayload'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Replay Replay Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CreateRequest:
      properties:
        name:
          type: string
          minLength: 1
          title: Name
      additionalProperties: false
      type: object
      required:
      - name
      title: CreateRequest
    ExecutionArtifactRequest:
      properties:
        execution_contract:
          $ref: '#/components/schemas/ExecutionContract'
      additionalProperties: false
      type: object
      required:
      - execution_contract
      title: ExecutionArtifactRequest
    ExecutionBudgetPayload:
      properties:
        max_latency_ms:
          anyOf:
          - type: integer
          - type: 'null'
          title: Max Latency Ms
        max_memory_mb:
          anyOf:
          - type: integer
          - type: 'null'
          title: Max Memory Mb
        max_error:
          anyOf:
          - type: number
          - type: 'null'
          title: Max Error
      additionalProperties: false
      type: object
      title: ExecutionBudgetPayload
    ExecutionContract:
      type: string
      enum:
      - deterministic
      - non_deterministic
      title: ExecutionContract
    ExecutionRequestPayload:
      properties:
        artifact_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Artifact Id
        request_text:
          anyOf:
          - type: string
          - type: 'null'
          title: Request Text
        vector:
          anyOf:
          - items:
              type: number
            type: array
          - type: 'null'
          title: Vector
        top_k:
          type: integer
          exclusiveMinimum: 0.0
          title: Top K
          default: 5
        execution_contract:
          $ref: '#/components/schemas/ExecutionContract'
        execution_intent:
          type: string
          title: Execution Intent
        execution_mode:
          type: string
          title: Execution Mode
          default: strict
        execution_budget:
          anyOf:
          - $ref: '#/components/schemas/ExecutionBudgetPayload'
          - type: 'null'
        randomness_profile:
          anyOf:
          - $ref: '#/components/schemas/RandomnessProfilePayload'
          - type: 'null'
      additionalProperties: false
      type: object
      required:
      - execution_contract
      - execution_intent
      title: ExecutionRequestPayload
    ExplainRequest:
      properties:
        result_id:
          type: string
          minLength: 1
          title: Result Id
        artifact_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Artifact Id
      additionalProperties: false
      type: object
      required:
      - result_id
      title: ExplainRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    IngestRequest:
      properties:
        documents:
          items:
            type: string
          type: array
          title: Documents
        vectors:
          items:
            items:
              type: number
            type: array
          type: array
          title: Vectors
      additionalProperties: false
      type: object
      required:
      - documents
      - vectors
      title: IngestRequest
    RandomnessProfilePayload:
      properties:
        seed:
          anyOf:
          - type: integer
          - type: 'null'
          title: Seed
        sources:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Sources
        bounded:
          type: boolean
          title: Bounded
          default: false
      additionalProperties: false
      type: object
      title: RandomnessProfilePayload
    BackendCapabilitiesReport:
      properties:
        backend:
          type: string
          title: Backend
        contracts:
          items:
            type: string
          type: array
          title: Contracts
        deterministic_query:
          type: boolean
          title: Deterministic Query
        supports_ann:
          type: boolean
          title: Supports Ann
        replayable:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Replayable
        metrics:
          items:
            type: string
          type: array
          title: Metrics
        max_vector_size:
          anyOf:
          - type: integer
          - type: 'null'
          title: Max Vector Size
        isolation_level:
          anyOf:
          - type: string
          - type: 'null'
          title: Isolation Level
        execution_modes:
          items:
            type: string
          type: array
          title: Execution Modes
        ann_status:
          type: string
          title: Ann Status
        storage_backends:
          items:
            $ref: '#/components/schemas/StorageBackendDescriptor'
          type: array
          title: Storage Backends
      additionalProperties: false
      type: object
      required:
      - backend
      - contracts
      - deterministic_query
      - supports_ann
      - metrics
      - execution_modes
      - ann_status
      - storage_backends
      title: BackendCapabilitiesReport
    StorageBackendDescriptor:
      properties:
        name:
          type: string
          title: Name
        status:
          type: string
          title: Status
        persistence:
          anyOf:
          - type: string
          - type: 'null'
          title: Persistence
        notes:
          anyOf:
          - type: string
          - type: 'null'
          title: Notes
      additionalProperties: false
      type: object
      required:
      - name
      - status
      title: StorageBackendDescriptor
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
