# Stub for optional hnswlib dependency used by ReferenceAnnRunner

from __future__ import annotations

from typing import Iterable, Tuple, Sequence

class Index:
    def __init__(self, space: str, dim: int, seed: int | None = ...) -> None: ...
    def init_index(self, max_elements: int, ef_construction: int = ..., M: int = ...) -> None: ...
    def add_items(self, data: Iterable[Tuple[float, ...]], ids: Iterable[int]) -> None: ...
    def knn_query(self, data: Sequence[Sequence[float]], k: int = ...) -> tuple[list[list[int]], list[list[float]]]: ...
    def set_ef(self, ef: int) -> None: ...
    def save_index(self, path: str) -> None: ...
    def load_index(self, path: str, max_elements: int = ...) -> None: ...
    @property
    def ef(self) -> int: ...

__all__ = ["Index"]
